apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend   # 👈 مهم جدًا
  template:
    metadata:
      labels:
        app: frontend   # 👈 لازم نفس الكلمة
    spec:
      containers:
        - name: frontend
          image: ahmed7amed9/frontend:latest
          ports:
            - containerPort: 80