apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
    - http:
        paths:
          # 👇 API + Swagger الأول (مهم الترتيب)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          # 👇 frontend في الآخر
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80