- hosts: servers
  become: true

  tasks:


    # 🟢 تثبيت Docker
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    # 🧹 حذف أي k3s قديم (مهم)
    - name: Remove old k3s
      shell: |
        /usr/local/bin/k3s-uninstall.sh || true

    # 🔥 تثبيت k3s صح
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_EXEC="--write-kubeconfig-mode=644" sh -
      args:
        executable: /bin/bash

    # 🟢 تأكد إنه شغال
    - name: Ensure k3s is running
      systemd:
        name: k3s
        state: started
        enabled: yes

    # 🟢 استنى لحد ما يبقى Ready
    - name: Wait for k3s
      shell: |
        sudo /usr/local/bin/k3s kubectl get nodes
      register: result
      retries: 15
      delay: 10
      until: result.rc == 0

    # 🟢 نسخ kubeconfig
    - name: Copy kubeconfig
      shell: |
        sudo cp /etc/rancher/k3s/k3s.yaml /home/ec2-user/kubeconfig

    - name: Fix ownership
      file:
        path: /home/ec2-user/kubeconfig
        owner: ec2-user
        group: ec2-user

    # 🔥 Deploy Nginx
    - name: Deploy Nginx
      shell: |
        sudo /usr/local/bin/k3s kubectl create deployment nginx --image=nginx || true
        sudo /usr/local/bin/k3s kubectl expose deployment nginx --port=80 --type=NodePort || true

    # 🔥 Deploy Jenkins (صح)
    - name: Deploy Jenkins
      shell: |
        sudo /usr/local/bin/k3s kubectl create namespace jenkins || true

        sudo /usr/local/bin/k3s kubectl create deployment jenkins \
          --image=jenkins/jenkins:lts \
          -n jenkins || true

        sudo /usr/local/bin/k3s kubectl expose deployment jenkins \
          --port=8080 --type=NodePort \
          -n jenkins || true